packages:
  - docs/
  - packages/*
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
catalog:
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  '@types/react': '^19.0.0'
  '@types/react-dom': '^19.0.0'
